name: Publish PowerShell Module

on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Build and publish
        uses: actions/checkout@v3
        env:
          NUGET_KEY: ${{ secrets.BENPULIDOPSGALLERY }}
          shell: pwsh
      - run: ./Build.ps1
      - run: Publish-Module -Path ./Artifacts -NuGetApiKey $env:BENPULIDOPSGALLERY -Verbose