name: Publish PowerShell Module

on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Build and publish
        uses: actions/checkout@v4
      - run: ./Build.ps1
        shell: pwsh
        env:
          NuGetApiKey: ${{ secrets.BENPULIDOPSGALLERY }}
