name: Publish PowerShell Module

on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Build and publish
        uses: actions/checkout@v3
      - run: ./Build.ps1
        shell: pwsh
      - run: Publish-Module -Path /home/runner/work/OGraph/OGraph/artifacts -NuGetApiKey ${{ secrets.BENPULIDOPSGALLERY }} -Verbose
        shell: pwsh